insert into animal  values (1, 'Mouse');
insert into animal  values (2, 'Cat');
insert into animal  values (3, 'Dog');
insert into animal  values (4, 'Elephant');
insert into animal  values (5, 'Elephant 5');
insert into animal  values (6, 'Elephant 6');
insert into animal  values (7, 'Elephant 7');
insert into animal  values (8, 'Elephant 8');
insert into animal  values (9, 'Elephant 9');
insert into animal  values (10, 'Elephant 10');
insert into animal  values (11, 'Elephant 11');
insert into animal  values (12, 'Elephant 12');
insert into animal  values (13, 'Elephant 13');
insert into animal  values (14, 'Elephant 14');
insert into animal  values (15, 'Elephant 15');
insert into animal  values (16, 'Elephant 16');
insert into animal  values (17, 'Elephant 17');
insert into animal  values (18, 'Elephant 18');
insert into animal  values (19, 'Elephant 19');
insert into animal  values (20, 'Elephant 20');